language: java
jdk: oraclejdk8
before_install:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- 'sed -i "s/^\(version: \).*$/\1$main_version.$TRAVIS_BUILD_NUMBER/g" src/main/resources/plugin.yml'
- pushd ~/build/
- git clone --depth=1 https://github.com/NyaaCat/NyaaCore NyaaCat/NyaaCore
- export NYAACORE_LANG_DIR=`readlink -f ./NyaaCat/NyaaCore/src/main/resources/lang/`
- popd
after_success:
- 'cp build/libs/nyaautils.jar ./nyaautils-$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER.jar'
before_deploy:
- export GIT_TAG=$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER
- export GIT_ORIGIN_URL=`git config --get remote.origin.url`
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GITHUB_KEY:@github.com" > .git/credentials
- git push -q --follow-tags
- gem install octokit -v 4.3.0
- gradle publish
- cd ..
- git clone -b maven-repo $GIT_ORIGIN_URL nyaautils-mvn
- cp -r nyaautils/build/repo/cat nyaautils-mvn/
- cd nyaautils-mvn
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GITHUB_KEY:@github.com" > .git/credentials
- git add .
- git commit -m "auto generated maven repo"
- git push --follow-tags
- cd ../nyaautils
deploy:
- provider: releases
  skip_cleanup: true
  prerelease: true
  api_key: ${GITHUB_DEPLOY_KEY}
  file: './nyaautils-$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER.jar'
  on:
    tags: false
    all_branches: true
branches:
  except:
  - "/^*-v[0-9]/"
  - "maven-repo"
env:
  global:
    - main_version=3
    - trigger_ci=20170624
